id: P30E6890B
initial_creation_type: ocr
source_metadata:
  volumes:
    4bb7ea1b8ee74e4486268facc4507f45:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: ཞིབ་མོ་རྣམ་པར་འཐག་པ་ཞེས་བྱ་བའི་མདོ།
      total_pages: 1605
      volume_number: 57
